basic.forever(function () {
    music.play(music.createSoundExpression(WaveShape.Noise, 1, 5000, 255, 255, 5000, SoundExpressionEffect.Vibrato, InterpolationCurve.Logarithmic), music.PlaybackMode.UntilDone)
    music.play(music.createSoundExpression(WaveShape.Sawtooth, 500, 500, 255, 0, 5000, SoundExpressionEffect.Tremolo, InterpolationCurve.Linear), music.PlaybackMode.UntilDone)
    music.play(music.createSoundExpression(WaveShape.Sawtooth, 500, 500, 255, 0, 50, SoundExpressionEffect.Vibrato, InterpolationCurve.Linear), music.PlaybackMode.UntilDone)
    music.play(music.createSoundExpression(WaveShape.Sawtooth, 500, 500, 255, 0, 50, SoundExpressionEffect.Vibrato, InterpolationCurve.Linear), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 B - C5 B - A G ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 A G F - - - - ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 B - C5 B - A G ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 A G F - - - - ", 120), music.PlaybackMode.UntilDone)
})
